<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.00">
  <Style>
    <showPageNumber>1</showPageNumber>
    <showPageNumberOne>1</showPageNumberOne>
    <pageNumberOddEven>1</pageNumberOddEven>
    <showMeasureNumber>1</showMeasureNumber>
    <showMeasureNumberOne>0</showMeasureNumberOne>
    <measureNumberInterval>5</measureNumberInterval>
    <measureNumberSystem>1</measureNumberSystem>
    <measureNumberAllStaffs>0</measureNumberAllStaffs>
    <showHeader>1</showHeader>
    <headerFirstPage>1</headerFirstPage>
    <headerOddEven>1</headerOddEven>
    <evenHeaderL></evenHeaderL>
    <evenHeaderC></evenHeaderC>
    <evenHeaderR></evenHeaderR>
    <oddHeaderL></oddHeaderL>
    <oddHeaderC></oddHeaderC>
    <oddHeaderR></oddHeaderR>
    <showFooter>1</showFooter>
    <footerFirstPage>1</footerFirstPage>
    <footerOddEven>1</footerOddEven>
    <evenFooterL>$P&#xA;KPM</evenFooterL>
    <evenFooterC></evenFooterC>
    <evenFooterR></evenFooterR>
    <oddFooterL></oddFooterL>
    <oddFooterC></oddFooterC>
    <oddFooterR>$P&#xA;KPM</oddFooterR>
  </Style>
</museScore>